### ISSUE TITLE
Scripts may benefit from general refactoring

### ISSUE THREAD

**Issue by hexacyanide** [asayler/COG-Web#28]
I've been working with the JavaScript files for a while, and thought they might benefit from some improvements. Here is a list:

- functions are not namespaced and are all defined in the global scope
- there are nested function declarations (is considered an anti-pattern due to hoisting)
- debug information is always shown (a dedicated debug library would be beneficial)
- naming conventions and whitespace use are inconsistent

If not too unnecessary, I would like to rework most of the scripts.

**Comment by asayler** [comment]
By all means, have at it. I'm not really a JS programmer, so I'm sure there is plenty of room for improvement. I know just enough JS to build stuff like this for the backend APIs that are more my forte.

**Comment by asayler** [comment]
Fixed via https://github.com/asayler/COG-Web/pull/29.
