### ISSUE TITLE
No Error on Bad Login

### ISSUE THREAD

**Issue by asayler** [asayler/COG-Web#31]
Since 4c20130, the login screen spins forever if the user supplies bad login credentials. It should instead return an error to the user indicating a failed login attempt.

From the error log:

```
debug.js:439: cog-web:page:login attempting to authenticate user `student1` +4s
https://test.api.cog.csel.io/my/token/: Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)
login.js:34: Uncaught ReferenceError: error is not defined
```

**Comment by hexacyanide** [comment]
Thanks for the catch - I've opened a PR that should fix this.
